name: Setup Rust
description: "Set up rust nightly"

inputs:
  components:
    description: "passed to actions-rust-lang/setup-rust-toolchain"
    default: ""
  cache:
    description: ""
    default: "true"
outputs:
  rust:
    description: setup rust output
    value: ${{ toJSON(steps.rust.outputs) }}
runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      uses: rui314/setup-mold@9c9c13bf4c3f1adef0cc596abc155580bcb04444
    - id: rust
      uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
      env:
        # renovate: datasource=custom.rust.nightly depName=x86_64-unknown-linux-gnu
        RUST_VERSION: nightly-2026-04-14
      with:
        toolchain: ${{ env.RUST_VERSION }}
        components: ${{ inputs.components }}
        cache: ${{ inputs.cache }}
        override: 'true'
    - run: |
        mkdir .cargo
        mv .github/actions_config.toml .cargo/config.toml
      shell: bash
