name: Setup Rust
description: "Set up rust nightly"

inputs:
  components:
    description: "passed to actions-rust-lang/setup-rust-toolchain"
    default: ""
  cache:
    description: ""
    default: "true"
outputs:
  rust:
    description: setup rust output
    value: ${{ toJSON(steps.rust.outputs) }}
runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      uses: rui314/setup-mold@9c9c13bf4c3f1adef0cc596abc155580bcb04444
    - id: rust
      uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
      env:
        # renovate: datasource=rust-version depName=rust-nightly
        RUST_VERSION: nightly-2026-05-13
      with:
        toolchain: ${{ env.RUST_VERSION }}
        components: ${{ inputs.components }}
        cache: ${{ inputs.cache }}
        override: 'true'
    - run: |
        mkdir .cargo
        cp .github/actions_config.toml .cargo/config.toml
      shell: bash
