name: "Run cargo-msrv"
on:
  workflow_dispatch:
  push:
    paths: ["**/Cargo.toml", "**/Cargo.lock"]
    branches: ["**", "!v2"]
    
jobs:
  cargo-msrv:
    uses: iiiii7d/cargo-msrv-workflow/.github/workflows/workflow.yml@6890b88602b5d7600258ace4185eb080751b96a5 # main
