name: "Run cargo-msrv"
on:
  workflow_dispatch:
  push:
    paths: ["**/Cargo.toml", "**/Cargo.lock"]
    branches: ["**", "!v2"]

jobs:
  cargo-msrv:
    permissions:
      contents: write
      pull-requests: write
    uses: iiiii7d/cargo-msrv-workflow/.github/workflows/workflow.yml@a059634e2d74b4051adcf92c3440759b99aaf8ec # main
