on:
  workflow_dispatch:
  push:
    paths: ["**/Cargo.toml", "**/Cargo.lock"]
    branches: ["dev"]
    
jobs:
  cargo-msrv:
    uses: iiiii7d/cargo-msrv-workflow/.github/workflows/workflow.yml@ff63cf91e4351cefcc084b589d8a6618d9eab59c # main
