on:
  push:
    branches: [ "**", "!v2" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/mise
        with:
          envs: ''
      - run: cd pla3 && cargo test --all-features --all-targets -- --nocapture